using System.Security.Cryptography;

namespace Delp.Core.Tools.Hashing;

/// <summary>
/// MongoDB ObjectId generation and decoding: a 12-byte value rendered as 24 lowercase hex
/// digits — a 4-byte Unix-second timestamp, a 5-byte value that stays fixed for this process
/// (crypto-random, standing in for MongoDB's "random per process" field), and a 3-byte counter
/// that increments (with wraparound) for every id generated by this process.
/// </summary>
public static class ObjectIdTool
{
    public const int MaxBatch = 1000;

    private static readonly byte[] ProcessRandom = RandomNumberGenerator.GetBytes(5);
    private static int _counter = RandomNumberGenerator.GetInt32(0, 1 << 24);
    private static readonly object Gate = new();

    /// <summary>Generates one ObjectId for the current instant.</summary>
    public static string Generate() => Generate(DateTimeOffset.UtcNow);

    public static string Generate(DateTimeOffset timestamp)
    {
        var bytes = new byte[12];
        var seconds = (uint)timestamp.ToUnixTimeSeconds();
        bytes[0] = (byte)(seconds >> 24);
        bytes[1] = (byte)(seconds >> 16);
        bytes[2] = (byte)(seconds >> 8);
        bytes[3] = (byte)seconds;
        Array.Copy(ProcessRandom, 0, bytes, 4, 5);

        int counter;
        lock (Gate)
        {
            counter = _counter;
            _counter = (_counter + 1) & 0xFF_FFFF;
        }
        bytes[9] = (byte)(counter >> 16);
        bytes[10] = (byte)(counter >> 8);
        bytes[11] = (byte)counter;

        return Convert.ToHexStringLower(bytes);
    }

    /// <exception cref="ArgumentException">Count is outside 1..1000.</exception>
    public static IReadOnlyList<string> GenerateBatch(int count)
    {
        if (count is < 1 or > MaxBatch)
            throw new ArgumentException($"Count must be between 1 and {MaxBatch}.", nameof(count));

        var results = new List<string>(count);
        for (var i = 0; i < count; i++)
            results.Add(Generate());
        return results;
    }

    public sealed record Decoded(DateTimeOffset Timestamp, string ProcessRandomHex, int Counter);

    /// <exception cref="FormatException">The text is not exactly 24 hex digits.</exception>
    public static Decoded Decode(string objectId)
    {
        ArgumentNullException.ThrowIfNull(objectId);
        var s = objectId.Trim();
        if (s.Length != 24 || !s.All(Uri.IsHexDigit))
            throw new FormatException("An ObjectId must be exactly 24 hex digits.");

        var bytes = Convert.FromHexString(s);
        var seconds = ((uint)bytes[0] << 24) | ((uint)bytes[1] << 16) | ((uint)bytes[2] << 8) | bytes[3];
        var timestamp = DateTimeOffset.FromUnixTimeSeconds(seconds);
        var randomHex = Convert.ToHexStringLower(bytes, 4, 5);
        var counter = (bytes[9] << 16) | (bytes[10] << 8) | bytes[11];
        return new Decoded(timestamp, randomHex, counter);
    }
}
