namespace Delp.Core.Tools.DevUtilities;

public static partial class GitignoreData
{
    private static readonly IReadOnlyList<GitignoreTemplate> FrameworkTemplates =
    [
        new("Unity", "Frameworks",
            """
            # This .gitignore file should be placed at the root of your Unity project directory
            #
            # Get latest from https://github.com/github/gitignore/blob/main/Unity.gitignore
            #
            # Recommended: add any editor/OS/tool-specific ignore rules from the Global/ templates as needed.
            # See: https://github.com/github/gitignore/tree/main/Global
            #
            .utmp/
            /[Ll]ibrary/
            /[Tt]emp/
            /[Oo]bj/
            /[Bb]uild/
            /[Bb]uilds/
            /[Ll]ogs/
            /[Uu]ser[Ss]ettings/
            *.log
            
            # By default unity supports Blender asset imports, *.blend1 blender files do not need to be commited to version control.
            *.blend1
            *.blend1.meta
            
            # MemoryCaptures can get excessive in size.
            # They also could contain extremely sensitive data
            /[Mm]emoryCaptures/
            
            # Recordings can get excessive in size
            /[Rr]ecordings/
            
            # Uncomment this line if you wish to ignore the asset store tools plugin
            # /[Aa]ssets/AssetStoreTools*
            
            # Autogenerated Jetbrains Rider plugin
            /[Aa]ssets/Plugins/Editor/JetBrains*
            # Jetbrains Rider personal-layer settings
            *.DotSettings.user
            
            # Visual Studio cache directory
            .vs/
            
            # Gradle cache directory
            .gradle/
            
            # Autogenerated VS/MD/Consulo solution and project files
            ExportedObj/
            .consulo/
            *.csproj
            *.unityproj
            *.sln
            *.slnx
            *.suo
            *.tmp
            *.user
            *.userprefs
            *.pidb
            *.booproj
            *.svd
            *.pdb
            *.mdb
            *.opendb
            *.VC.db
            
            # Unity3D generated meta files
            *.pidb.meta
            *.pdb.meta
            *.mdb.meta
            
            # Unity3D generated file on crash reports
            sysinfo.txt
            
            # Mono auto generated files
            mono_crash.*
            
            # Builds
            *.apk
            *.aab
            *.unitypackage
            *.unitypackage.meta
            *.app
            
            # Crashlytics generated file
            crashlytics-build.properties
            
            # TestRunner generated files
            InitTestScene*.unity*
            
            # Addressables default ignores, before user customizations
            /ServerData
            /[Aa]ssets/StreamingAssets/aa*
            /[Aa]ssets/AddressableAssetsData/link.xml*
            /[Aa]ssets/Addressables_Temp*
            # By default, Addressables content builds will generate addressables_content_state.bin
            # files in platform-specific subfolders, for example:
            # /Assets/AddressableAssetsData/OSX/addressables_content_state.bin
            /[Aa]ssets/AddressableAssetsData/*/*.bin*
            
            # Visual Scripting auto-generated files
            /[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db
            /[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db.meta
            /[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers
            /[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers.meta
            
            # Auto-generated scenes by play mode tests
            /[Aa]ssets/[Ii]nit[Tt]est[Ss]cene*.unity*
            
            # Auto-generated cache in Assets folder
            /[Aa]ssets/[Ss]ceneDependencyCache*
            """
        ),
        new("UnrealEngine", "Frameworks",
            """
            # Visual Studio 2015 user specific files
            .vs/
            
            # Compiled Object files
            *.slo
            *.lo
            *.o
            *.obj
            
            # Precompiled Headers
            *.gch
            *.pch
            
            # Compiled Dynamic libraries
            *.so
            *.dylib
            *.dll
            
            # Fortran module files
            *.mod
            
            # Compiled Static libraries
            *.lai
            *.la
            *.a
            *.lib
            
            # Executables
            *.exe
            *.out
            *.app
            *.ipa
            
            # These project files can be generated by the engine
            *.xcodeproj
            *.xcworkspace
            *.sln
            *.suo
            *.opensdf
            *.sdf
            *.VC.db
            *.VC.opendb
            .vsconfig
            
            # Precompiled Assets
            SourceArt/**/*.png
            SourceArt/**/*.tga
            
            # Binary Files
            Binaries/*
            Plugins/**/Binaries/*
            
            # Builds
            Build/*
            
            # Whitelist PakBlacklist-<BuildConfiguration>.txt files
            !Build/*/
            Build/*/**
            !Build/*/PakBlacklist*.txt
            
            # Don't ignore icon files in Build
            !Build/**/*.ico
            
            # Built data for maps
            *_BuiltData.uasset
            
            # Configuration files generated by the Editor
            Saved/*
            
            # Compiled source files for the engine to use
            Intermediate/*
            Plugins/**/Intermediate/*
            
            # Cache files for the editor to use
            DerivedDataCache/*
            """
        ),
        new("Android", "Frameworks",
            """
            # Gradle files
            .gradle/
            build/
            
            # Local configuration file (sdk path, etc)
            local.properties
            
            # Log/OS Files
            *.log
            
            # Android Studio generated files and folders
            captures/
            .externalNativeBuild/
            .cxx/
            *.aab
            *.apk
            output-metadata.json
            
            # IntelliJ
            *.iml
            .idea/
            misc.xml
            deploymentTargetDropDown.xml
            render.experimental.xml
            
            # Keystore files
            *.jks
            *.keystore
            
            # Google Services (e.g. APIs or Firebase)
            google-services.json
            
            # Android Profiling
            *.hprof
            """
        ),
        new("Xcode", "Frameworks",
            """
            ## User settings
            xcuserdata/
            """
        ),
        new("Django", "Frameworks",
            """
            *.log
            *.pot
            *.pyc
            __pycache__/
            local_settings.py
            db.sqlite3
            db.sqlite3-journal
            media
            
            # If your build process includes running collectstatic, then you probably
            # don't need or want to include staticfiles/ in your Git repository. Update
            # and uncomment the following line accordingly.
            # <django-project-name>/staticfiles/
            """
        ),
        new("Rails", "Frameworks",
            """
            *.rbc
            capybara-*.html
            .rspec
            /db/*.sqlite3
            /db/*.sqlite3-journal
            /db/*.sqlite3-[0-9]*
            /public/system
            /coverage/
            /spec/tmp
            *.orig
            rerun.txt
            pickle-email-*.html
            
            # Ignore all logfiles and tempfiles.
            /log/*
            /tmp/*
            !/log/.keep
            !/tmp/.keep
            
            # TODO Comment out this rule if you are OK with secrets being uploaded to the repo
            config/initializers/secret_token.rb
            config/master.key
            
            # Only include if you have production secrets in this file, which is no longer a Rails default
            # config/secrets.yml
            
            # dotenv, dotenv-rails
            # TODO Comment out these rules if environment variables can be committed
            .env
            .env*.local
            
            ## Environment normalization:
            /.bundle
            /vendor/bundle
            
            # these should all be checked in to normalize the environment:
            # Gemfile.lock, .ruby-version, .ruby-gemset
            
            # unless supporting rvm < 1.11.0 or doing something fancy, ignore this:
            .rvmrc
            
            # if using bower-rails ignore default bower_components path bower.json files
            /vendor/assets/bower_components
            *.bowerrc
            bower.json
            
            # Ignore pow environment settings
            .powenv
            
            # Ignore Byebug command history file.
            .byebug_history
            
            # Ignore node_modules
            node_modules/
            
            # Ignore precompiled javascript packs
            /public/packs
            /public/packs-test
            /public/assets
            
            # Ignore yarn files
            /yarn-error.log
            yarn-debug.log*
            .yarn-integrity
            
            # Ignore uploaded files in development
            /storage/*
            !/storage/.keep
            /public/uploads
            """
        ),
        new("Laravel", "Frameworks",
            """
            /vendor/
            node_modules/
            npm-debug.log
            yarn-error.log
            
            # Laravel 4 specific
            bootstrap/compiled.php
            app/storage/
            
            # Laravel 5 & Lumen specific
            public/storage
            public/hot
            
            # Laravel 5 & Lumen specific with changed public path
            public_html/storage
            public_html/hot
            
            storage/*.key
            .env
            Homestead.yaml
            Homestead.json
            /.vagrant
            .phpunit.result.cache
            
            /public/build
            /storage/pail
            .env.backup
            .env.production
            .phpactor.json
            auth.json
            """
        ),
        new("Terraform", "Frameworks",
            """
            # Local .terraform directories
            .terraform/
            
            # .tfstate files
            *.tfstate
            *.tfstate.*
            
            # Crash log files
            crash.log
            crash.*.log
            
            # Exclude all .tfvars files, which are likely to contain sensitive data, such as
            # password, private keys, and other secrets. These should not be part of version
            # control as they are data points which are potentially sensitive and subject
            # to change depending on the environment.
            *.tfvars
            *.tfvars.json
            
            # Ignore override files as they are usually used to override resources locally and so
            # are not checked in
            override.tf
            override.tf.json
            *_override.tf
            *_override.tf.json
            
            # Ignore transient lock info files created by terraform apply
            .terraform.tfstate.lock.info
            
            # Include override files you do wish to add to version control using negated pattern
            # !example_override.tf
            
            # Include tfplan files to ignore the plan output of command: terraform plan -out=tfplan
            # example: *tfplan*
            
            # Ignore CLI configuration files
            .terraformrc
            terraform.rc
            
            # Optional: ignore graph output files generated by `terraform graph`
            # *.dot
            
            # Optional: ignore plan files saved before destroying Terraform configuration
            # Uncomment the line below if you want to ignore planout files.
            # planout
            """
        ),
        new("Ansible", "Frameworks",
            """
            # The default root path for Ansible config files on the controller
            .ansible/
            
            # Retry files generated for failed Ansible playbook runs
            *.retry
            """
        ),
        new("Gradle", "Frameworks",
            """
            .gradle
            **/build/
            !**/src/**/build/
            
            # Ignore Gradle GUI config
            gradle-app.setting
            
            # Avoid ignoring Gradle wrapper jar file (.jar files are usually ignored)
            !gradle-wrapper.jar
            
            # Avoid ignore Gradle wrapper properties
            !gradle-wrapper.properties
            
            # Cache of project
            .gradletasknamecache
            
            # Eclipse Gradle plugin generated files
            # Eclipse Core
            .project
            # JDT-specific (Eclipse Java Development Tools)
            .classpath
            """
        ),
        new("Maven", "Frameworks",
            """
            target/
            pom.xml.tag
            pom.xml.releaseBackup
            pom.xml.versionsBackup
            pom.xml.next
            release.properties
            dependency-reduced-pom.xml
            buildNumber.properties
            .mvn/timing.properties
            # https://maven.apache.org/tools/wrapper/#Usage_with_or_without_Binary_JAR
            .mvn/wrapper/maven-wrapper.jar
            
            # Eclipse m2e generated files
            # Eclipse Core
            .project
            # JDT-specific (Eclipse Java Development Tools)
            .classpath
            """
        ),
        new("Flutter", "Frameworks",
            """
            # Miscellaneous
            *.class
            *.lock
            *.log
            *.pyc
            *.swp
            .buildlog/
            .history
            
            
            
            # Flutter repo-specific
            /bin/cache/
            /bin/internal/bootstrap.bat
            /bin/internal/bootstrap.sh
            /bin/mingit/
            /dev/benchmarks/mega_gallery/
            /dev/bots/.recipe_deps
            /dev/bots/android_tools/
            /dev/devicelab/ABresults*.json
            /dev/docs/doc/
            /dev/docs/flutter.docs.zip
            /dev/docs/lib/
            /dev/docs/pubspec.yaml
            /dev/integration_tests/**/xcuserdata
            /dev/integration_tests/**/Pods
            /packages/flutter/coverage/
            version
            analysis_benchmark.json
            
            # packages file containing multi-root paths
            .packages.generated
            
            # Flutter/Dart/Pub related
            **/doc/api/
            .dart_tool/
            .flutter-plugins
            .flutter-plugins-dependencies
            **/generated_plugin_registrant.dart
            .packages
            .pub-preload-cache/
            .pub/
            build/
            flutter_*.png
            linked_*.ds
            unlinked.ds
            unlinked_spec.ds
            
            # Android related
            **/android/**/gradle-wrapper.jar
            .gradle/
            **/android/captures/
            **/android/gradlew
            **/android/gradlew.bat
            **/android/local.properties
            **/android/**/GeneratedPluginRegistrant.java
            **/android/key.properties
            *.jks
            
            # iOS/XCode related
            **/ios/**/*.mode1v3
            **/ios/**/*.mode2v3
            **/ios/**/*.moved-aside
            **/ios/**/*.pbxuser
            **/ios/**/*.perspectivev3
            **/ios/**/*sync/
            **/ios/**/.sconsign.dblite
            **/ios/**/.tags*
            **/ios/**/.vagrant/
            **/ios/**/DerivedData/
            **/ios/**/Icon?
            **/ios/**/Pods/
            **/ios/**/.symlinks/
            **/ios/**/profile
            **/ios/**/xcuserdata
            **/ios/.generated/
            **/ios/Flutter/.last_build_id
            **/ios/Flutter/App.framework
            **/ios/Flutter/Flutter.framework
            **/ios/Flutter/Flutter.podspec
            **/ios/Flutter/Generated.xcconfig
            **/ios/Flutter/ephemeral
            **/ios/Flutter/app.flx
            **/ios/Flutter/app.zip
            **/ios/Flutter/flutter_assets/
            **/ios/Flutter/flutter_export_environment.sh
            **/ios/ServiceDefinitions.json
            **/ios/Runner/GeneratedPluginRegistrant.*
            
            # macOS
            **/Flutter/ephemeral/
            **/Pods/
            **/macos/Flutter/GeneratedPluginRegistrant.swift
            **/macos/Flutter/ephemeral
            **/xcuserdata/
            
            # Windows
            **/windows/flutter/generated_plugin_registrant.cc
            **/windows/flutter/generated_plugin_registrant.h
            **/windows/flutter/generated_plugins.cmake
            
            # Linux
            **/linux/flutter/generated_plugin_registrant.cc
            **/linux/flutter/generated_plugin_registrant.h
            **/linux/flutter/generated_plugins.cmake
            
            # Coverage
            coverage/
            
            # Symbols
            app.*.symbols
            
            # Exceptions to above rules.
            !**/ios/**/default.mode1v3
            !**/ios/**/default.mode2v3
            !**/ios/**/default.pbxuser
            !**/ios/**/default.perspectivev3
            !/packages/flutter_tools/test/data/dart_dependencies_test/**/.packages
            !/dev/ci/**/Gemfile.lock
            """
        ),
        new("WordPress", "Frameworks",
            """
            # WordPress - ignore core, configuration, examples, uploads and logs.
            # https://github.com/github/gitignore/blob/main/WordPress.gitignore
            
            # Core
            #
            # Note: if you want to stage/commit WP core files
            # you can delete this whole section/until Configuration.
            /wp-admin/
            /wp-content/index.php
            /wp-content/languages
            /wp-content/plugins/index.php
            /wp-content/themes/index.php
            /wp-includes/
            /index.php
            /license.txt
            /readme.html
            /wp-*.php
            /xmlrpc.php
            
            # Configuration
            wp-config.php
            
            # Example themes
            /wp-content/themes/twenty*/
            
            # Example plugin
            /wp-content/plugins/hello.php
            
            # Uploads
            /wp-content/uploads/
            
            # Log files
            *.log
            
            # htaccess
            /.htaccess
            
            # All plugins
            #
            # Note: If you wish to whitelist plugins,
            # uncomment the next line
            #/wp-content/plugins
            
            # All themes
            #
            # Note: If you wish to whitelist themes,
            # uncomment the next line
            #/wp-content/themes
            """
        ),
    ];
}
