using System.Globalization;

namespace Delp.Core.Tools.DevUtilities;

/// <summary>One HTTP status code with human-readable guidance.</summary>
public sealed record HttpStatusEntry(
    int Code,
    string Name,
    string Class,
    string Summary,
    string When,
    string? Rfc);

/// <summary>Reference data for HTTP status codes, covering the full IANA registry plus a few well-known unofficial codes.</summary>
public static class HttpStatusData
{
    public const string Informational = "Informational";
    public const string Success = "Success";
    public const string Redirection = "Redirection";
    public const string ClientError = "Client Error";
    public const string ServerError = "Server Error";

    public static IReadOnlyList<HttpStatusEntry> All { get; } = BuildAll();

    /// <summary>Group label ("1xx".."5xx") for a status code, for the class-filter UI.</summary>
    public static string GroupLabel(int code) => $"{code / 100}xx";

    /// <summary>Matches by code prefix, name, or summary text.</summary>
    public static IReadOnlyList<HttpStatusEntry> Search(string? query)
    {
        if (string.IsNullOrWhiteSpace(query))
            return All;

        var q = query.Trim();
        return All.Where(e =>
                e.Code.ToString(CultureInfo.InvariantCulture).StartsWith(q, StringComparison.OrdinalIgnoreCase) ||
                e.Name.Contains(q, StringComparison.OrdinalIgnoreCase) ||
                e.Summary.Contains(q, StringComparison.OrdinalIgnoreCase) ||
                e.When.Contains(q, StringComparison.OrdinalIgnoreCase))
            .ToList();
    }

    private static List<HttpStatusEntry> BuildAll()
    {
        const string c1 = Informational, c2 = Success, c3 = Redirection, c4 = ClientError, c5 = ServerError;

        return new List<HttpStatusEntry>
        {
            new(100, "Continue", c1,
                "The server has received the request headers and the client should proceed to send the request body.",
                "Sent in response to a request with an `Expect: 100-continue` header, before the client uploads a large body, so it isn't sent if the server would reject it outright.",
                "RFC 9110 §15.2.1"),
            new(101, "Switching Protocols", c1,
                "The server is switching to the protocol requested by the client's `Upgrade` header.",
                "Used when upgrading a connection in place, e.g. HTTP/1.1 to WebSocket.",
                "RFC 9110 §15.2.2"),
            new(102, "Processing", c1,
                "The server has accepted a WebDAV request but processing will take time.",
                "Keeps the client from timing out while the server works through a long-running WebDAV operation.",
                "RFC 2518 (obsoleted by RFC 4918)"),
            new(103, "Early Hints", c1,
                "A preliminary response sent before the final response, hinting at resources the client can start preloading.",
                "Let a browser start fetching CSS or fonts referenced by `Link` headers while the server is still assembling the page.",
                "RFC 8297"),

            new(200, "OK", c2,
                "The request succeeded, and the response body (if any) contains the requested representation.",
                "The default success response for GET/PUT/POST when no more specific 2xx code fits better.",
                "RFC 9110 §15.3.1"),
            new(201, "Created", c2,
                "The request succeeded and a new resource was created as a result.",
                "Return from a POST or PUT that creates a resource; include a `Location` header pointing at it.",
                "RFC 9110 §15.3.2"),
            new(202, "Accepted", c2,
                "The request has been accepted for processing, but processing is not complete.",
                "Use for asynchronous work queues where the result isn't ready yet — give the client a status URL to poll.",
                "RFC 9110 §15.3.3"),
            new(203, "Non-Authoritative Information", c2,
                "The returned metadata is from a local or third-party copy, not the origin server.",
                "Rare — used by transforming proxies that modify the origin's response before passing it on.",
                "RFC 9110 §15.3.4"),
            new(204, "No Content", c2,
                "The request succeeded but there is no body to return.",
                "Common for DELETE or PUT requests where the client doesn't need a representation back.",
                "RFC 9110 §15.3.5"),
            new(205, "Reset Content", c2,
                "The request succeeded; the client should reset the document view that submitted it.",
                "Tells a browser to clear the form that was just submitted.",
                "RFC 9110 §15.3.6"),
            new(206, "Partial Content", c2,
                "The server is delivering only part of the resource, as requested by a `Range` header.",
                "Used for resumable downloads and byte-range video streaming.",
                "RFC 9110 §15.3.7"),
            new(207, "Multi-Status", c2,
                "Conveys multiple independent status codes for the sub-operations of a single WebDAV request.",
                "Batch operations (e.g. COPY across many resources) where each item can succeed or fail independently.",
                "RFC 4918"),
            new(208, "Already Reported", c2,
                "Members of a WebDAV binding were already listed by a previous entry and won't be repeated.",
                "Avoids re-enumerating the same resource multiple times when a multi-status response has shared bindings.",
                "RFC 5842"),
            new(226, "IM Used", c2,
                "The server fulfilled the request using one or more instance manipulations applied to the current instance.",
                "Used with delta encoding to return a diff against a known base instance instead of the full resource.",
                "RFC 3229"),

            new(300, "Multiple Choices", c3,
                "The request has multiple possible representations and the client must pick one.",
                "Rarely used in practice — most APIs prefer content negotiation via the `Accept` header instead.",
                "RFC 9110 §15.4.1"),
            new(301, "Moved Permanently", c3,
                "The resource has permanently moved to a new URI.",
                "Use for permanent redirects that search engines and caches should remember; note that some old clients turn a POST into a GET on 301.",
                "RFC 9110 §15.4.2"),
            new(302, "Found", c3,
                "The resource temporarily resides at a different URI.",
                "The historically ambiguous redirect — prefer 303 or 307 in new code so the method-preservation behavior is explicit.",
                "RFC 9110 §15.4.3"),
            new(303, "See Other", c3,
                "The response to the request can be found at another URI and should be retrieved with GET.",
                "Use after a state-changing POST to redirect to a GET-able result page (the post/redirect/get pattern).",
                "RFC 9110 §15.4.4"),
            new(304, "Not Modified", c3,
                "The client's cached copy is still valid, so no body is sent.",
                "Returned when `If-None-Match` or `If-Modified-Since` show the cached representation is current.",
                "RFC 9110 §15.4.5"),
            new(305, "Use Proxy", c3,
                "The requested resource must be accessed through the proxy given in the response.",
                "Deprecated for security reasons — most clients ignore it, so avoid relying on it.",
                "RFC 9110 §15.4.6 (deprecated)"),
            new(307, "Temporary Redirect", c3,
                "The resource temporarily resides at a different URI; the request method must not change.",
                "Use instead of 302 when the client must resubmit the same HTTP method, including the POST body, to the new URI.",
                "RFC 9110 §15.4.8"),
            new(308, "Permanent Redirect", c3,
                "The resource has permanently moved; the request method must not change.",
                "Use instead of 301 when the method and body must be preserved, e.g. a permanently relocated API endpoint.",
                "RFC 9110 §15.4.9"),

            new(400, "Bad Request", c4,
                "The server could not understand the request due to malformed syntax.",
                "Use for malformed JSON, missing required fields, or invalid parameter formats — the request itself is broken, not just semantically wrong.",
                "RFC 9110 §15.5.1"),
            new(401, "Unauthorized", c4,
                "Authentication is required and has failed or has not been provided.",
                "Return when credentials are missing or invalid; the response must include a `WWW-Authenticate` challenge header.",
                "RFC 9110 §15.5.2"),
            new(402, "Payment Required", c4,
                "Reserved for future use.",
                "Occasionally repurposed by APIs for billing or quota errors, e.g. an exceeded paid usage limit, though no standard semantics exist.",
                "RFC 9110 §15.5.3"),
            new(403, "Forbidden", c4,
                "The server understood the request but refuses to authorize it.",
                "Use when the caller is authenticated but lacks permission — unlike 401, retrying with different credentials on the same account won't help.",
                "RFC 9110 §15.5.4"),
            new(404, "Not Found", c4,
                "The server can't find the requested resource.",
                "Use for unknown routes or IDs, or to hide the existence of a resource from an unauthorized caller instead of returning 403.",
                "RFC 9110 §15.5.5"),
            new(405, "Method Not Allowed", c4,
                "The request method is not supported for this resource.",
                "Return when the route exists but the HTTP verb doesn't; include an `Allow` header listing the supported methods.",
                "RFC 9110 §15.5.6"),
            new(406, "Not Acceptable", c4,
                "No representation matching the request's `Accept` headers can be produced.",
                "Use when strict content negotiation fails and there is no acceptable fallback format.",
                "RFC 9110 §15.5.7"),
            new(407, "Proxy Authentication Required", c4,
                "The client must authenticate with a proxy before the request can proceed.",
                "Like 401 but for a proxy in front of the server; the response must include `Proxy-Authenticate`.",
                "RFC 9110 §15.5.8"),
            new(408, "Request Timeout", c4,
                "The server timed out waiting for the request.",
                "Sent by a server that closes an idle connection because the client was too slow sending the request.",
                "RFC 9110 §15.5.9"),
            new(409, "Conflict", c4,
                "The request conflicts with the current state of the target resource.",
                "Use for edit conflicts, e.g. an optimistic-concurrency version mismatch, or creating a resource that already exists.",
                "RFC 9110 §15.5.10"),
            new(410, "Gone", c4,
                "The resource is permanently gone and no forwarding address is known.",
                "Prefer over 404 when you know a resource used to exist but was deliberately removed — lets caches purge it confidently.",
                "RFC 9110 §15.5.11"),
            new(411, "Length Required", c4,
                "The server requires a `Content-Length` header that was not supplied.",
                "Return when chunked or otherwise unsized bodies aren't accepted for this endpoint.",
                "RFC 9110 §15.5.12"),
            new(412, "Precondition Failed", c4,
                "One of the conditional request headers (`If-Match`, `If-Unmodified-Since`, …) evaluated to false.",
                "Use for optimistic concurrency control — the client's known version doesn't match the server's current state.",
                "RFC 9110 §15.5.13"),
            new(413, "Content Too Large", c4,
                "The request body is larger than the server is willing or able to process.",
                "Return when an upload exceeds a configured size limit; add a `Retry-After` header if the limit is only temporary.",
                "RFC 9110 §15.5.14"),
            new(414, "URI Too Long", c4,
                "The request target is longer than the server is willing to interpret.",
                "Common when a GET request encodes too much data in the query string — switch to POST or a shorter identifier.",
                "RFC 9110 §15.5.15"),
            new(415, "Unsupported Media Type", c4,
                "The payload format is not supported by the server for this method or resource.",
                "Use when `Content-Type` doesn't match what the endpoint accepts, e.g. XML sent to a JSON-only API.",
                "RFC 9110 §15.5.16"),
            new(416, "Range Not Satisfiable", c4,
                "None of the ranges in the request's `Range` header overlap the resource.",
                "Returned for byte-range requests past the end of a resource; include `Content-Range: bytes */<size>`.",
                "RFC 9110 §15.5.17"),
            new(417, "Expectation Failed", c4,
                "The expectation given in the request's `Expect` header could not be met.",
                "Rare in practice — mostly seen with misbehaving `Expect: 100-continue` clients or proxies.",
                "RFC 9110 §15.5.18"),
            new(418, "I'm a Teapot", c4,
                "The server refuses to brew coffee because it is, permanently, a teapot.",
                "An April Fools' joke from the Hyper Text Coffee Pot Control Protocol. Some frameworks use it in examples or tests, but avoid it in production APIs.",
                "RFC 2324 §2.3.2"),
            new(421, "Misdirected Request", c4,
                "The request was directed at a server that cannot produce a response for the scheme and authority requested.",
                "Happens with HTTP/2 connection reuse when a request lands on a server that isn't authoritative for the requested host.",
                "RFC 9110 §15.5.20"),
            new(422, "Unprocessable Content", c4,
                "The request is well-formed but semantically invalid — it fails business validation.",
                "Prefer over 400 when the syntax is fine but the values don't make sense, e.g. an email field that isn't a valid email address.",
                "RFC 9110 §15.5.21"),
            new(423, "Locked", c4,
                "The resource being accessed is locked.",
                "WebDAV: another client currently holds a lock on the resource, e.g. someone else is editing the same file.",
                "RFC 4918"),
            new(424, "Failed Dependency", c4,
                "The request failed because it depended on another request that failed.",
                "WebDAV batch operations: a step is skipped because an earlier step in the same request failed.",
                "RFC 4918"),
            new(425, "Too Early", c4,
                "The server is unwilling to process a request that might be replayed.",
                "Sent when a request arrives as TLS 0-RTT early data and could be a replay attack — the client should retry after the full handshake completes.",
                "RFC 8470"),
            new(426, "Upgrade Required", c4,
                "The server refuses to perform the request using the current protocol.",
                "Use to force clients onto a newer protocol version, e.g. requiring TLS or HTTP/2 via the `Upgrade` header.",
                "RFC 9110 §15.5.22"),
            new(428, "Precondition Required", c4,
                "The origin server requires the request to be conditional.",
                "Prevents the 'lost update' problem by forcing clients to send `If-Match` before updating a resource they haven't re-fetched.",
                "RFC 6585"),
            new(429, "Too Many Requests", c4,
                "The client has sent too many requests in a given period of time (rate limiting).",
                "Include a `Retry-After` header telling well-behaved clients how long to back off.",
                "RFC 6585"),
            new(431, "Request Header Fields Too Large", c4,
                "The request's header fields are too large for the server to process.",
                "Often caused by oversized cookies or an accumulated `Referer`/auth header chain — trim headers before retrying.",
                "RFC 6585"),
            new(451, "Unavailable For Legal Reasons", c4,
                "The resource is unavailable due to a legal demand, such as a takedown or censorship order.",
                "Named after Ray Bradbury's 'Fahrenheit 451'; include details of the legal restriction in the body where possible.",
                "RFC 7725"),

            new(500, "Internal Server Error", c5,
                "A generic, unexpected condition prevented the server from fulfilling the request.",
                "The catch-all for unhandled exceptions — prefer a more specific 5xx code when the cause is known.",
                "RFC 9110 §15.6.1"),
            new(501, "Not Implemented", c5,
                "The server doesn't support the functionality required to fulfill the request.",
                "Use when a method or feature is recognized but not, or not yet, implemented on this server.",
                "RFC 9110 §15.6.2"),
            new(502, "Bad Gateway", c5,
                "A server acting as a gateway or proxy received an invalid response from the upstream server.",
                "Typical when a reverse proxy, such as nginx or a load balancer, can't get a valid response from your app server.",
                "RFC 9110 §15.6.3"),
            new(503, "Service Unavailable", c5,
                "The server is temporarily unable to handle the request, due to overload or maintenance.",
                "Include a `Retry-After` header so well-behaved clients know when to try again instead of hammering the server.",
                "RFC 9110 §15.6.4"),
            new(504, "Gateway Timeout", c5,
                "A gateway or proxy did not receive a timely response from the upstream server.",
                "The upstream service took too long to respond — check for slow database queries or downstream outages.",
                "RFC 9110 §15.6.5"),
            new(505, "HTTP Version Not Supported", c5,
                "The server doesn't support the HTTP protocol version used in the request.",
                "Extremely rare today — nearly every server supports at least HTTP/1.1.",
                "RFC 9110 §15.6.6"),
            new(506, "Variant Also Negotiates", c5,
                "The server has an internal configuration error: the chosen variant for transparent content negotiation itself negotiates.",
                "Indicates a negotiation loop in the server's content-negotiation setup — a server misconfiguration, not a client error.",
                "RFC 2295"),
            new(507, "Insufficient Storage", c5,
                "The server can't store the representation needed to complete the request.",
                "WebDAV: the server ran out of disk space or quota while processing the request.",
                "RFC 4918"),
            new(508, "Loop Detected", c5,
                "The server detected an infinite loop while processing a request with `Depth: infinity`.",
                "WebDAV: the request revisited a resource it had already processed via shared bindings.",
                "RFC 5842"),
            new(510, "Not Extended", c5,
                "Further extensions to the request are required for the server to fulfill it.",
                "Signals that a required HTTP extension policy wasn't satisfied — very rarely encountered in the wild.",
                "RFC 2774"),
            new(511, "Network Authentication Required", c5,
                "The client needs to authenticate to gain network access, e.g. behind a captive portal.",
                "Returned by intercepting proxies, such as hotel or airport Wi-Fi, instead of the actual target response until the user logs in.",
                "RFC 6585"),
        };
    }
}
