using System.Text;
using QRCoder;

namespace Delp.Core.Tools.DevUtilities;

/// <summary>Error-correction level for a generated QR code.</summary>
public enum QrEccLevel
{
    L,
    M,
    Q,
    H,
}

/// <summary>Wi-Fi authentication type embedded in a WIFI: QR payload.</summary>
public enum WifiAuth
{
    Wpa,
    Wep,
    None,
}

/// <summary>Generates QR code images and well-known QR payload strings. Pure byte-array output — no System.Drawing dependency.</summary>
public static class QrTool
{
    /// <summary>Renders <paramref name="content"/> as a PNG-encoded QR code.</summary>
    /// <exception cref="FormatException">Content is empty.</exception>
    public static byte[] CreatePng(string content, int pixelsPerModule, QrEccLevel level)
    {
        if (string.IsNullOrEmpty(content))
            throw new FormatException("Enter some text or a URL to generate a QR code.");
        if (pixelsPerModule is < 1 or > 100)
            throw new ArgumentOutOfRangeException(nameof(pixelsPerModule), pixelsPerModule, "Pixels per module must be between 1 and 100.");

        var eccLevel = ToEccLevel(level);

        using var generator = new QRCodeGenerator();
        using var data = generator.CreateQrCode(content, eccLevel);
        using var png = new PngByteQRCode(data);
        return png.GetGraphic(pixelsPerModule, drawQuietZones: true);
    }

    private static QRCodeGenerator.ECCLevel ToEccLevel(QrEccLevel level) => level switch
    {
        QrEccLevel.L => QRCodeGenerator.ECCLevel.L,
        QrEccLevel.M => QRCodeGenerator.ECCLevel.M,
        QrEccLevel.Q => QRCodeGenerator.ECCLevel.Q,
        QrEccLevel.H => QRCodeGenerator.ECCLevel.H,
        _ => throw new ArgumentOutOfRangeException(nameof(level), level, null),
    };

    /// <summary>
    /// Builds the de-facto <c>WIFI:</c> QR payload (as generated by Android/iOS Wi-Fi QR sharing) that lets a
    /// camera app join a network without typing the password.
    /// </summary>
    /// <exception cref="FormatException">SSID is empty, or a password is required but missing.</exception>
    public static string WifiPayload(string ssid, string? password, WifiAuth auth, bool hidden)
    {
        if (string.IsNullOrEmpty(ssid))
            throw new FormatException("SSID is required for a Wi-Fi QR code.");
        if (auth != WifiAuth.None && string.IsNullOrEmpty(password))
            throw new FormatException("A password is required for WPA/WEP networks.");

        var authToken = auth switch
        {
            WifiAuth.Wpa => "WPA",
            WifiAuth.Wep => "WEP",
            WifiAuth.None => "nopass",
            _ => throw new ArgumentOutOfRangeException(nameof(auth), auth, null),
        };

        var sb = new StringBuilder("WIFI:");
        sb.Append("T:").Append(authToken).Append(';');
        sb.Append("S:").Append(EscapeField(ssid)).Append(';');
        if (auth != WifiAuth.None)
            sb.Append("P:").Append(EscapeField(password!)).Append(';');
        if (hidden)
            sb.Append("H:true;");
        sb.Append(';');
        return sb.ToString();
    }

    /// <summary>Escapes the special characters reserved by the WIFI: payload grammar (<c>; , : " \</c>).</summary>
    private static string EscapeField(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            if (c is ';' or ',' or ':' or '"' or '\\')
                sb.Append('\\');
            sb.Append(c);
        }
        return sb.ToString();
    }
}
