namespace Delp.Core.Tools.DevUtilities;

public static partial class ShortcutCheatSheetData
{
    private static readonly IReadOnlyList<ShortcutEntry> VimEntries =
    [
        // Motions
        new("Move left", "Motions", "h"),
        new("Move down", "Motions", "j"),
        new("Move up", "Motions", "k"),
        new("Move right", "Motions", "l"),
        new("Next word start", "Motions", "w"),
        new("Next WORD start (whitespace-separated)", "Motions", "W"),
        new("Previous word start", "Motions", "b"),
        new("Previous WORD start", "Motions", "B"),
        new("End of word", "Motions", "e"),
        new("End of WORD", "Motions", "E"),
        new("End of previous word", "Motions", "ge"),
        new("Start of line", "Motions", "0"),
        new("First non-blank character of line", "Motions", "^"),
        new("End of line", "Motions", "$"),
        new("Last non-blank character of line", "Motions", "g_"),
        new("Go to first line", "Motions", "gg"),
        new("Go to last line", "Motions", "G"),
        new("Go to line N", "Motions", "{N}G", "Also works as :N in command mode."),
        new("Jump to matching bracket", "Motions", "%"),
        new("Previous blank-line paragraph", "Motions", "{"),
        new("Next blank-line paragraph", "Motions", "}"),
        new("Next sentence", "Motions", ")"),
        new("Previous sentence", "Motions", "("),
        new("Top of screen", "Motions", "H"),
        new("Middle of screen", "Motions", "M"),
        new("Bottom of screen", "Motions", "L"),
        new("Scroll half page down", "Motions", "Ctrl+d"),
        new("Scroll half page up", "Motions", "Ctrl+u"),
        new("Scroll full page forward", "Motions", "Ctrl+f"),
        new("Scroll full page backward", "Motions", "Ctrl+b"),
        new("Find next occurrence of a character on the line", "Motions", "f{char}"),
        new("Find previous occurrence of a character on the line", "Motions", "F{char}"),
        new("Till just before next occurrence of a character", "Motions", "t{char}"),
        new("Till just after previous occurrence of a character", "Motions", "T{char}"),
        new("Repeat last f/t/F/T", "Motions", ";"),
        new("Repeat last f/t/F/T, reversed", "Motions", ","),

        // Editing
        new("Insert before cursor", "Editing", "i"),
        new("Insert at start of line", "Editing", "I"),
        new("Append after cursor", "Editing", "a"),
        new("Append at end of line", "Editing", "A"),
        new("Open new line below and insert", "Editing", "o"),
        new("Open new line above and insert", "Editing", "O"),
        new("Delete character under cursor", "Editing", "x"),
        new("Delete character before cursor", "Editing", "X"),
        new("Delete line", "Editing", "dd"),
        new("Delete word", "Editing", "dw"),
        new("Delete to end of line", "Editing", "d$", "D is a shorthand for the same thing."),
        new("Delete to start of line", "Editing", "d0"),
        new("Delete inside word/quotes/brackets (text object)", "Editing", "di{obj}", "e.g. diw, di\", dib."),
        new("Change line", "Editing", "cc"),
        new("Change word", "Editing", "cw"),
        new("Change inside word/quotes/brackets (text object)", "Editing", "ci{obj}", "e.g. ciw, ci\", cib."),
        new("Change to end of line", "Editing", "C"),
        new("Replace single character", "Editing", "r{char}"),
        new("Enter Replace mode (overtype)", "Editing", "R"),
        new("Yank (copy) line", "Editing", "yy"),
        new("Yank word", "Editing", "yw"),
        new("Paste after cursor/line", "Editing", "p"),
        new("Paste before cursor/line", "Editing", "P"),
        new("Undo", "Editing", "u"),
        new("Redo", "Editing", "Ctrl+r"),
        new("Repeat last change", "Editing", "."),
        new("Join line with next", "Editing", "J"),
        new("Join line with next, no inserted space", "Editing", "gJ"),
        new("Toggle case of character under cursor", "Editing", "~"),
        new("Lowercase current line", "Editing", "guu"),
        new("Uppercase current line", "Editing", "gUU"),
        new("Indent line", "Editing", ">>"),
        new("Unindent line", "Editing", "<<"),
        new("Auto-indent line", "Editing", "=="),
        new("Delete character and enter insert mode", "Editing", "s"),

        // Visual
        new("Enter visual (character) mode", "Visual", "v"),
        new("Enter visual line mode", "Visual", "V"),
        new("Enter visual block mode", "Visual", "Ctrl+v"),
        new("Reselect last visual selection", "Visual", "gv"),
        new("Jump to other end of selection", "Visual", "o"),
        new("Delete selection", "Visual", "d"),
        new("Yank selection", "Visual", "y"),
        new("Change selection", "Visual", "c"),
        new("Indent selection", "Visual", ">"),
        new("Unindent selection", "Visual", "<"),
        new("Auto-indent selection", "Visual", "="),
        new("Uppercase selection", "Visual", "U"),
        new("Lowercase selection", "Visual", "u"),
        new("Insert at start of each line (visual block)", "Visual", "I", "Only applies once you press Esc after typing."),
        new("Append at end of each line (visual block)", "Visual", "A", "Only applies once you press Esc after typing."),

        // Search & Replace
        new("Search forward", "Search & Replace", "/{pattern}"),
        new("Search backward", "Search & Replace", "?{pattern}"),
        new("Repeat search, same direction", "Search & Replace", "n"),
        new("Repeat search, opposite direction", "Search & Replace", "N"),
        new("Search word under cursor, forward", "Search & Replace", "*"),
        new("Search word under cursor, backward", "Search & Replace", "#"),
        new("Replace all occurrences in file", "Search & Replace", ":%s/old/new/g"),
        new("Replace all occurrences with confirmation", "Search & Replace", ":%s/old/new/gc"),
        new("Replace first match on current line", "Search & Replace", ":s/old/new/"),
        new("Replace in a visual selection only", "Search & Replace", ":'<,'>s/old/new/g", "Vim fills in '<,'> automatically after a visual selection."),
        new("Clear search highlighting", "Search & Replace", ":noh"),
        new("Select next search match (for a change)", "Search & Replace", "gn"),
        new("Change next search match", "Search & Replace", "cgn", "Combine with . to repeat a rename across matches."),

        // Windows & Tabs
        new("Split window horizontally", "Windows & Tabs", ":split", "Or the chord Ctrl+w s."),
        new("Split window vertically", "Windows & Tabs", ":vsplit", "Or the chord Ctrl+w v."),
        new("Cycle to next window", "Windows & Tabs", "Ctrl+w w"),
        new("Move to window in direction", "Windows & Tabs", "Ctrl+w h/j/k/l"),
        new("Close current window", "Windows & Tabs", "Ctrl+w q"),
        new("Equalize window sizes", "Windows & Tabs", "Ctrl+w ="),
        new("Maximize current window", "Windows & Tabs", "Ctrl+w _"),
        new("Open a new tab", "Windows & Tabs", ":tabnew"),
        new("Next tab", "Windows & Tabs", "gt"),
        new("Previous tab", "Windows & Tabs", "gT"),
        new("Go to tab number N", "Windows & Tabs", "{N}gt"),
        new("Close current tab", "Windows & Tabs", ":tabclose"),
        new("Close all other tabs", "Windows & Tabs", ":tabonly"),

        // Marks, Registers & Macros
        new("Set mark a-z", "Marks, Registers & Macros", "m{a-z}"),
        new("Jump to mark, exact position", "Marks, Registers & Macros", "`{a-z}"),
        new("Jump to mark, start of line", "Marks, Registers & Macros", "'{a-z}"),
        new("Jump to position before last jump", "Marks, Registers & Macros", "``"),
        new("Yank into named register", "Marks, Registers & Macros", "\"{reg}y"),
        new("Paste from named register", "Marks, Registers & Macros", "\"{reg}p"),
        new("Paste from the yank register (unaffected by deletes)", "Marks, Registers & Macros", "\"0p"),
        new("Record macro into register a-z", "Marks, Registers & Macros", "q{a-z} ... q"),
        new("Play macro a", "Marks, Registers & Macros", "@a"),
        new("Repeat last played macro", "Marks, Registers & Macros", "@@"),
        new("Play macro a N times", "Marks, Registers & Macros", "{N}@a"),
        new("Open the command-line window (edit history)", "Marks, Registers & Macros", "q:"),
        new("List all marks", "Marks, Registers & Macros", ":marks"),
        new("List all registers", "Marks, Registers & Macros", ":registers"),

        // Files
        new("Save file", "Files", ":w"),
        new("Quit", "Files", ":q"),
        new("Save and quit", "Files", ":wq", "Or :x, which only writes if there are changes."),
        new("Quit without saving", "Files", ":q!"),
        new("Edit a file", "Files", ":e {file}"),
        new("Reload file, discarding changes", "Files", ":e!"),
        new("Save and quit (normal mode)", "Files", "ZZ"),
        new("Quit without saving (normal mode)", "Files", "ZQ"),
        new("Save under a new name", "Files", ":sav {file}"),
        new("Write and quit all windows", "Files", ":wqa"),
    ];
}
